# GitHub Sponsors config file for jmcaamanog
# https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [jmcaamanog]
